### ISSUE TITLE
[Epic] Blog Improvements 

### ISSUE THREAD

**Issue by adelaidemt** [blinkk/editor.dev-ui#202]
- [ ] Handling draft/published/scheduled content
- [ ] Enable users to add inline assets with text on L/R sides of image
- [ ] Handling draft/published/scheduled content
